FIX ruby 2.7 compatibility
Bundler needs to be required along with its cli, otherwise the following
raises:
```
bundler/cli.rb:111:in `<class:CLI>':
undefined method `feature_flag' for Bundler:Module (NoMethodError)
```